# Powerlevel10k Configuration
# Generated by p10k configure wizard
# ~/.p10k.zsh

# Temporarily change options
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases' ]] || p10k_config_opts+=('aliases')
builtin 'setopt' 'no_aliases'
'builtin' 'source' "${ZSH:C}/themes/powerlevel10k/config/p10k-lean.zsh"

# Prompt style: lean
POWERLEVEL9K_MODE=nerdfont-complete
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs time)

# Directory
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_SHORTEN_DELIMITER=..
POWERLEVEL9K_DIR_MAX_LENGTH=30
POWERLEVEL9K_DIR_BACKGROUND=blue
POWERLEVEL9K_DIR_FOREGROUND=black

# Git
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=green
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=black
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=yellow
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=black
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=red
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=black
POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=true

# Status
POWERLEVEL9K_STATUS_OK=true
POWERLEVEL9K_STATUS_OK_FOREGROUND=green
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=red

# Time
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
POWERLEVEL9K_TIME_BACKGROUND=black

# Instant prompt
typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

# Restore options
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' '-v' 'p10k_config_opts'