# Termux Properties
# ~/.termux/termux.properties

# Extra keys row
extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]

# Appearance
use-black-ui = true
font-size = 16
cursor-style = bar
cursor-blink-rate = 500

# Behavior
bell-character = ignore
vibrate-key = ignore
back-key = quit
terminal-transcript-hidden = true

# Colors
background-color = #1e1e2e
foreground-color = #cdd6f4
cursor-color = #f5e0dc